# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'netease-music-swiftui' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for netease-music-swiftui
  pod 'Alamofire'  
  pod 'Kingfisher'
  pod 'WCDB.swift'
  pod 'ExytePopupView', '2.0.0'

  target 'netease-music-swiftuiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'netease-music-swiftuiUITests' do
    # Pods for testing
  end

end
